version: '3.5'
services:

  db:
    image: postgres:11
    container_name: mirrorbrain-db
    volumes:
      - "/data/db:/var/lib/postgresql/data"
    command: postgres -c shared_buffers=256MB -c max_connections=200
    restart: always

  mirrorbrain-backup:
    image: kiwix/borg-backup
    container_name: mirrorbrain-backup
    links:
      - db
    env_file:
      - .env_mirrorbrain_backup
    restart: always

  web:
    image: ghcr.io/kiwix/mirrorbrain
    container_name: mirrorbrain-web
    volumes:
      - "/data/download:/var/www/download.kiwix.org"
      - "/data/library:/var/www/library.kiwix.org"
      - "/data/hash:/usr/share/mirrorbrain"
      - "/data/geoip:/usr/local/geoip/share/GeoIP"
    environment:
      - UPDATE_HASH=1
      - HTTPD=1
      - VIRTUAL_HOST=download.kiwix.org
      - LETSENCRYPT_HOST=download.kiwix.org
      - LETSENCRYPT_EMAIL=contact@kiwix.org
      - HTTPS_METHOD=noredirect
    networks:
      default:
        aliases:
          - download
    links:
      - db
    restart: always

  download-backup:
    image: kiwix/borg-backup
    container_name: download-backup
    volumes:
      - "/data/openzim/README:/storage/openzim/README:ro"
      - "/data/openzim/robots.txt:/storage/openzim/robots.txt:ro"
      - "/data/openzim/archive:/storage/openzim/archive:ro"
      - "/data/openzim/release:/storage/openzim/release:ro"
      - "/data/openzim/wikifundi:/storage/openzim/wikifundi:ro"
      - "/data/download/README:/storage/kiwix/README:ro"
      - "/data/download/favicon.ico:/storage/kiwix/favicon.ico:ro"
      - "/data/download/robots.txt:/storage/kiwix/robots.txt:ro"
      - "/data/download/archive:/storage/kiwix/archive:ro"
      - "/data/download/dev:/storage/kiwix/dev:ro"
      - "/data/download/other:/storage/kiwix/other:ro"
      - "/data/download/release:/storage/kiwix/release:ro"
      - "/data/download/screenshots:/storage/kiwix/screenshots:ro"
      - "/data/zimfarm-drive:ro"
    env_file:
      - .env_download_backup
    restart: always

  update-db:
    image: ghcr.io/kiwix/mirrorbrain
    container_name: mirrorbrain-update
    volumes:
      - "/data/download:/var/www/download.kiwix.org"
      - "/data/openzim:/var/www/download.openzim.org"
    environment:
      - UPDATE_DB=1
    links:
      - db
    restart: always

  library:
    image: ghcr.io/kiwix/library
    container_name: library
    volumes:
      - "/data/library:/var/www/library.kiwix.org"
      - "/data/download:/var/www/download.kiwix.org"
    environment:
      - VIRTUAL_HOST=library.kiwix.org
      - LETSENCRYPT_HOST=library.kiwix.org
      - LETSENCRYPT_EMAIL=contact@kiwix.org
      - HTTPS_METHOD=noredirect
    secrets:
      - wiki-password
    restart: always

  dev-library:
    image: rgaudin/kiwix-tools:nightly
    command: /bin/sh -c "kiwix-serve /data/*.zim"
    container_name: dev-library
    volumes:
      - "/data/download/zim/.hidden/dev:/data:ro"
    environment:
      - VIRTUAL_HOST=dev.library.kiwix.org
      - LETSENCRYPT_HOST=dev.library.kiwix.org
      - LETSENCRYPT_EMAIL=contact@kiwix.org
      - HTTPS_METHOD=noredirect
    restart: always

  reverse-proxy:
    image: ghcr.io/kiwix/reverse-proxy
    container_name: reverse-proxy
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "vhost:/etc/nginx/vhost.d"
      - "/data/html:/usr/share/nginx/html"
      - "/data/openzim:/var/www/download.openzim.org"
      - "/data/download:/var/www/download.kiwix.org"
      - "/data/library:/var/www/library.kiwix.org"
      - "/data/tmp:/var/www/tmp.kiwix.org"
      - "/data/certs:/etc/nginx/certs:ro"
      - "/data/log/nginx:/var/log/nginx"
    environment:
      - VIRTUAL_HOST=download.openzim.org,mirror.download.kiwix.org,tmp.kiwix.org,monitoring.openzim.org,drive.farm.openzim.org
      - LETSENCRYPT_HOST=download.openzim.org,mirror.download.kiwix.org,tmp.kiwix.org,monitoring.openzim.org,drive.farm.openzim.org
      - LETSENCRYPT_EMAIL=contact@kiwix.org
      - HTTPS_METHOD=noredirect
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
    ports:
      - "80:80"
      - "443:443"
    networks:
      default:
        aliases:
          - mirror.download
          - tmp
    restart: always

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt
    depends_on:
      - reverse-proxy
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "vhost:/etc/nginx/vhost.d"
      - "/data/html:/usr/share/nginx/html"
      - "/data/certs:/etc/nginx/certs:rw"
    restart: always

  ftpd:
    image: gimoh/pureftpd
    container_name: ftpd
    ports:
      - "21:21"
      - "30000-30050:30000-30050"
    volumes:
      - "/data/download:/var/lib/ftp:ro"
    entrypoint:
      - /usr/local/sbin/dkr-init
      - -p
      - "30000:30050"
    restart: always

  rsyncd:
    image: ghcr.io/kiwix/rsyncd
    container_name: rsyncd
    ports:
      - "873:873"
    volumes:
      - "/data/download:/var/www/download.kiwix.org"
      - "/data/openzim:/var/www/download.openzim.org"
      - "/data/tmp:/var/www/tmp.kiwix.org"
    restart: always

  zimfarm-receiver:
    image: openzim/zimfarm-receiver
    container_name: zimfarm-receiver
    volumes:
      - "/data/zimfarm-warehouse/logs:/jail/logs:rw"
      - "/data/zimfarm-warehouse/zim:/jail/zim:rw"
      - "/data/log/zimquarantine:/mnt/check_logs:rw"
      - "/data/zimfarm-warehouse/quarantine:/mnt/quarantine:rw"
      - "/data/download/zim:/mnt/zim:rw"
    environment:
      - VALIDATION_OPTION=NO_CHECK
    ports:
      - "1522:22"
    restart: always

  zimfarm-watcher:
    image: openzim/zimfarm-watcher
    container_name: zimfarm-watcher
    command: watcher --debug --dir /data --threads 10 --zimfarm-username stackwatcher --dont-schedule-on-update --every 1d
    volumes:
      - "/data/download/zimfarm-watcher:/data:rw"
    secrets:
      - s3_url
      - zimfarm_password
    restart: always

  zimfarm-drive:
    image: ghcr.io/openzim/surfer
    container_name: zimfarm-drive
    volumes:
      - "/data/zimfarm-drive:/data"
    secrets:
      - drive-password
    environment:
      - VIRTUAL_HOST=drive.farm.openzim.org
      - LETSENCRYPT_HOST=drive.farm.openzim.org
      - LETSENCRYPT_EMAIL=contact@openzim.org
    ports:
      - "3000:3000"
    restart: always

  matomo-download:
    image: ghcr.io/kiwix/matomo-log-analytics
    container_name: matomo-log-analytics_download
    volumes:
      - "/data/log/nginx:/var/log/nginx"
    environment:
      - ID_SITE=2
      - URL=http://stats.kiwix.org
      - LOG=/var/log/nginx/access.log
      - HOST=download.kiwix.org
    secrets:
      - matomo-token
    restart: always

  matomo-download_openzim:
    image: ghcr.io/kiwix/matomo-log-analytics
    container_name: matomo-log-analytics_download_openzim
    volumes:
      - "/data/log/nginx:/var/log/nginx"
    environment:
      - ID_SITE=6
      - URL=http://stats.kiwix.org
      - LOG=/var/log/nginx/access.log
      - HOST=download.openzim.org
    secrets:
      - matomo-token
    restart: always

  monitoring:
    build: ./netdata
    container_name: monitoring
    volumes:
      - "/data/monitoring/cache:/var/cache/netdata"
      - "/etc/passwd:/host/etc/passwd:ro"
      - "/etc/group:/host/etc/group:ro"
      - "/proc:/host/proc:ro"
      - "/sys:/host/sys:ro"
      - "/etc/os-release:/host/etc/os-release:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    ports:
      - "19999:19999"
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor=unconfined
    restart: always

volumes:
  vhost:
secrets:
  matomo-token:
    file: ./matomo-token.txt
  wiki-password:
    file: ./wiki-password.txt
  s3_url:
    file: ./zimfarm-watcher-s3_url.txt
  zimfarm_password:
    file: ./zimfarm-watcher-zimfarm_password.txt
  drive-password:
    file: ./zimfarm-drive-password.txt
networks:
  default:
    name: kiwix.org
