version: '3.5'
services:

  db:
    image: postgres
    container_name: mirrorbrain-db
    volumes:
      - "/data/db:/var/lib/postgresql/data"
    restart: always

  web:
    image: kiwix/mirrorbrain
    container_name: mirrorbrain-web
    volumes:
      - "/data/download:/var/www/download.kiwix.org"
      - "/data/hash:/usr/share/mirrorbrain"
      - "/data/geoip:/usr/local/geoip/share/GeoIP"
    environment:
      - UPDATE_HASH=1
      - HTTPD=1
      - VIRTUAL_HOST=download.kiwix.org
      - LETSENCRYPT_HOST=download.kiwix.org
      - LETSENCRYPT_EMAIL=contact@kiwix.org
      - HTTPS_METHOD=noredirect
    networks:
      default:
        aliases:
          - download
    links:
      - db
    restart: always

  update-db:
    image: kiwix/mirrorbrain
    container_name: mirrorbrain-update
    volumes:
      - "/data/download:/var/www/download.kiwix.org"
      - "/data/openzim:/var/www/download.openzim.org"
    environment:
      - UPDATE_DB=1
    links:
      - db
    restart: always

  library:
    image: kiwix/library
    container_name: library
    volumes:
      - "/data/library:/var/www/library.kiwix.org"
      - "/data/download:/var/www/download.kiwix.org"
    environment:
      - VIRTUAL_HOST=library.kiwix.org
      - LETSENCRYPT_HOST=library.kiwix.org
      - LETSENCRYPT_EMAIL=contact@kiwix.org
      - HTTPS_METHOD=noredirect
    secrets:
      - wiki-password
    restart: always

  reverse-proxy:
    image: kiwix/reverse-proxy
    container_name: reverse-proxy
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "vhost:/etc/nginx/vhost.d"
      - "/data/html:/usr/share/nginx/html"
      - "/data/openzim:/var/www/download.openzim.org"
      - "/data/download:/var/www/download.kiwix.org"
      - "/data/library:/var/www/library.kiwix.org"
      - "/data/cardshop-download:/var/www/download.cardshop.hotspot.kiwix.org"
      - "/data/tmp:/var/www/tmp.kiwix.org"
      - "/data/certs:/etc/nginx/certs:ro"
      - "/data/log/nginx:/var/log/nginx"
      - "/data/zimfarm-warehouse/logs:/var/www/logs.warehouse.farm.openzim.org"
    environment:
      - VIRTUAL_HOST=download.openzim.org,mirror.download.kiwix.org,tmp.kiwix.org,download.cardshop.hotspot.kiwix.org,logs.warehouse.farm.openzim.org
      - LETSENCRYPT_HOST=download.openzim.org,mirror.download.kiwix.org,tmp.kiwix.org,download.cardshop.hotspot.kiwix.org,logs.warehouse.farm.openzim.org
      - LETSENCRYPT_EMAIL=contact@kiwix.org
      - HTTPS_METHOD=noredirect
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
    ports:
      - 80:80
      - 443:443
    networks:
      default:
        aliases:
          - mirror.download
          - tmp
          - download.cardshop.hotspot
          - logs.warehouse.farm.openzim.org
    restart: always

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt
    depends_on:
      - reverse-proxy
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "vhost:/etc/nginx/vhost.d"
      - "/data/html:/usr/share/nginx/html"
      - "/data/certs:/etc/nginx/certs:rw"
    restart: always

  ftpd:
    image: gimoh/pureftpd
    container_name: ftpd
    ports:
      - "21:21"
      - "30000-30050:30000-30050"
    volumes:
      - "/data/download:/var/lib/ftp"
    entrypoint:
      - /usr/local/sbin/dkr-init
      - -p
      - "30000:30050"
    restart: always

  rsyncd:
    image: kiwix/rsyncd
    container_name: rsyncd
    ports:
      - 873:873
    volumes:
      - "/data/download:/var/www/download.kiwix.org"
      - "/data/tmp:/var/www/tmp.kiwix.org"
    restart: always

  zimfarm-receiver:
    image: openzim/zimfarm-receiver
    container_name: zimfarm-receiver
    volumes:
      - "/data/zimfarm-warehouse/logs:/jail/logs:rw"
      - "/data/zimfarm-warehouse/zim:/jail/zim:rw"
      - "/data/log/zimquarantine:/mnt/check_logs:rw"
      - "/data/quarantine/zim:/mnt/quarantine:rw"
      - "/data/download/zim:/mnt/zim:rw"
    environment:
      - VALIDATION_OPTION=NO_QUARANTINE
    ports:
      - 1522:22
    restart: always

  matomo-download:
    image: kiwix/matomo-log-analytics
    container_name: matomo-log-analytics_download
    volumes:
      - "/data/log/nginx:/var/log/nginx"
    environment:
      - ID_SITE=2
      - URL=http://stats.kiwix.org
      - LOG=/var/log/nginx/access.log
      - HOST=download.kiwix.org
    secrets:
      - matomo-token
    restart: always
  matomo-download_openzim:
    image: kiwix/matomo-log-analytics
    container_name: matomo-log-analytics_download_openzim
    volumes:
      - "/data/log/nginx:/var/log/nginx"
    environment:
      - ID_SITE=6
      - URL=http://stats.kiwix.org
      - LOG=/var/log/nginx/access.log
      - HOST=download.openzim.org
    secrets:
      - matomo-token
    restart: always
volumes:
  vhost:
secrets:
  matomo-token:
    file: ./matomo-token.txt
  wiki-password:
    file: ./wiki-password.txt
networks:
  default:
    name: kiwix.org
