version: '3'
services:

  db:
    image: mysql:5
    container_name: matomo_mysql
    volumes:
      - "./data/mysql/conf:/etc/mysql/conf.d"
      - "/data/matomo/mysql/files:/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    restart: always

  app:
    image: ghcr.io/kiwix/matomo:latest
    container_name: matomo_app
    volumes:
      - "appdir:/var/www/html"
      - "/data/matomo/data:/var/www/html/misc/user"
    links:
      - db
    environment:
      - MATOMO_URL=http://stats
    restart: always

  web:
    image: nginx:latest
    container_name: matomo_web
    volumes:
      - "appdir:/var/www/html"
      - "/data/matomo/data:/var/www/html/misc/user"
      - "./data/web/vhost.d:/etc/nginx/conf.d"
    links:
      - app
    environment:
      - VIRTUAL_HOST=stats.kiwix.org
      - LETSENCRYPT_HOST=stats.kiwix.org
      - LETSENCRYPT_EMAIL=contact@kiwix.org
      - HTTPS_METHOD=redirect
    networks:
      default:
        aliases:
          - stats
    restart: always

  backup:
    image: kiwix/borg-backup
    container_name: matomo_backup
    volumes:
      - "/data/matomo/data:/storage:ro"
    links:
      - db
    env_file:
      - .env_backup
    restart: always

volumes:
  appdir:

networks:
  default:
    external:
      name: kiwix.org
