name: Kiwix-build container images

on:
  push:
    paths:
      - 'kiwix-build_ci/**'
  workflow_dispatch:

env:
  IMAGE_PREFIX: ghcr.io/kiwix/kiwix-build_ci_

jobs:
  Container:
    strategy:
      fail-fast: false
      matrix:
        platform: ['linux/amd64']
        variant: [f35, focal, jammy, x86-64_manylinux, alpine, noble, resolute]
        include:
          - variant: aarch64_manylinux
            platform: linux/arm64
    runs-on: ubuntu-22.04

    steps:
      - name: Get current date
        run: echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Setup container image name
        run: echo "IMAGE_NAME=${{ env.IMAGE_PREFIX }}${{ matrix.variant }}" >> $GITHUB_ENV

      - name: Set dev tag
        run: echo "TAGS=${{ env.IMAGE_NAME }}:dev" >> $GITHUB_ENV

      - name: Update production tags
        if: github.event.ref == 'refs/heads/main'
        run: echo "TAGS=${{ env.TAGS }},${{ env.IMAGE_NAME }}:${{ env.DATE }},${{ env.IMAGE_NAME }}:latest" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:kiwix-build_ci"
          file: ${{ matrix.variant }}_builder.dockerfile
          platforms: ${{ matrix.platform }}
          push: true
          tags: ${{ env.TAGS }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
